import type { OSKEvent } from "@/types";

export const EVENTS: OSKEvent[] = [
  {
    id: 1,
    slug: "osk-build-challenge-q3-2025",
    type: "hackathon",
    status: "upcoming",
    mode: "in-person",
    title: "OSK Build Challenge — Q3 2025",
    tagline: "48 hours. Real problems. Real code.",
    description:
      "Our biggest event of the year. Teams of 2–5 tackle real societal challenges in Rwanda using open-source tools. Mentors on standby. Cash prizes for the top three teams.",
    date: "July 26–27, 2025",
    dateShort: "Jul 26–27",
    day: 26,
    month: "JUL",
    year: 2025,
    time: "8:00 AM – 6:00 PM (both days)",
    location: "Kigali Innovation City, Rwanda",
    attendees: 78,
    capacity: 120,
    speakers: [
      { name: "Didas Mbarushimana", role: "Community Lead", initials: "DD" },
      { name: "Guest Mentor — TBA", role: "Industry Expert", initials: "GM" },
    ],
    tags: ["hackathon", "open source", "prizes"],
    featured: true,
    registerUrl: "https://forms.gle/osk-hackathon",
  },
  {
    id: 2,
    slug: "wednesday-session-apis-auth-july",
    type: "session",
    status: "upcoming",
    mode: "virtual",
    title: "Wednesday Tech Session — APIs & Authentication",
    tagline: "Build a secure Node.js API from scratch.",
    description:
      "Live coding session covering REST API design, JWT authentication, and deploying to Vercel. Bring your laptop.",
    date: "July 9, 2025",
    dateShort: "Jul 9",
    day: 9,
    month: "JUL",
    year: 2025,
    time: "7:00 PM – 8:30 PM",
    location: "Discord — #tech-session",
    attendees: 34,
    capacity: null,
    speakers: [{ name: "Tech Lead", role: "OSK Maintainer", initials: "TL" }],
    tags: ["node.js", "api", "auth"],
    featured: false,
    registerUrl: "https://discord.com/invite/3dTFZSn6Tq/osk",
  },
  {
    id: 3,
    slug: "july-monthly-meetup",
    type: "meetup",
    status: "upcoming",
    mode: "in-person",
    title: "July Monthly Meetup",
    tagline: "Projects, people, and real conversations.",
    description:
      "Showcase what you've built this month. Hear from maintainers. Meet new contributors. Light drinks. No slides required.",
    date: "July 5, 2025",
    dateShort: "Jul 5",
    day: 5,
    month: "JUL",
    year: 2025,
    time: "3:00 PM – 5:30 PM",
    location: "Norrsken Kigali",
    attendees: 51,
    capacity: 80,
    speakers: [
      { name: "Open mic", role: "All contributors welcome", initials: "OM" },
    ],
    tags: ["meetup", "networking", "showcase"],
    featured: false,
    registerUrl: "https://forms.gle/osk-meetup",
  },
  {
    id: 4,
    slug: "git-rebase-session-june",
    type: "session",
    status: "past",
    mode: "virtual",
    title: "Wednesday Session — Git Rebase Deep Dive",
    tagline: "Interactive history rewriting with confidence.",
    description:
      "A live walkthrough of git rebase, interactive rebase, and squashing commits on real OSK project history.",
    date: "June 25, 2025",
    dateShort: "Jun 25",
    day: 25,
    month: "JUN",
    year: 2025,
    time: "7:00 PM – 8:30 PM",
    location: "Discord",
    attendees: 47,
    capacity: null,
    speakers: [
      { name: "Jean-Paul Hakizimana", role: "OSK Contributor", initials: "JH" },
    ],
    tags: ["git", "rebase", "version control"],
    featured: false,
    registerUrl: "",
    recapUrl: "#",
    recordingUrl: "#",
  },
];
