// src/constants/resources.ts
import type { Resource } from "@/types";

export type ExternalTool = {
  name:        string;
  description: string;
  link:        string;
  iconKey:     string; // resolved to a React node in the component
  category:    string;
  free:        boolean;
};

export const RESOURCES: Resource[] = [
  {
    id:          1,
    slug:        "your-first-pull-request",
    type:        "tutorial",
    category:    "git",
    title:       "Your First Pull Request: A Complete Walkthrough",
    description: "Everything you need to go from zero to merged PR — forking, branching, committing, and opening a pull request against an OSK project. Written for absolute beginners.",
    author:      "Didas Mbarushimana",
    authorRole:  "Community Lead",
    readTime:    "12 min read",
    difficulty:  "beginner",
    tags:        ["git", "github", "open source", "beginner"],
    link:        "#",
    featured:    true,
    date:        "July 2025",
    views:       1240,
  },
  {
    id:          2,
    slug:        "how-to-read-a-codebase",
    type:        "guide",
    category:    "open-source",
    title:       "How to Read Someone Else's Codebase",
    description: "Jumping into an unfamiliar project is intimidating. This guide breaks down a repeatable system for understanding code you didn't write — fast.",
    author:      "Tech Lead",
    authorRole:  "OSK Maintainer",
    readTime:    "8 min read",
    difficulty:  "intermediate",
    tags:        ["codebase", "reading code", "open source"],
    link:        "#",
    featured:    false,
    date:        "June 2025",
    views:       876,
  },
  {
    id:          3,
    slug:        "git-rebase-vs-merge",
    type:        "video",
    category:    "git",
    title:       "Git Rebase vs Merge — Explained Simply",
    description: "A recorded OSK Wednesday session covering one of the most confusing Git concepts. Live examples, real project history, no hand-waving.",
    author:      "Jean-Paul H.",
    authorRole:  "OSK Contributor",
    readTime:    "28 min watch",
    difficulty:  "intermediate",
    tags:        ["git", "rebase", "merge", "version control"],
    link:        "#",
    featured:    false,
    date:        "June 2025",
    views:       653,
  },
  {
    id:          4,
    slug:        "osk-readme-template",
    type:        "template",
    category:    "open-source",
    title:       "OSK Project README Template",
    description: "A battle-tested README structure used across all OSK projects. Includes setup instructions, contribution guide, code of conduct, and roadmap sections.",
    author:      "Solange Mukamana",
    authorRole:  "Technical Writer",
    readTime:    "5 min setup",
    difficulty:  "beginner",
    tags:        ["readme", "documentation", "template"],
    link:        "#",
    featured:    false,
    date:        "May 2025",
    views:       990,
  },
  {
    id:          5,
    slug:        "nodejs-express-rest-api",
    type:        "tutorial",
    category:    "javascript",
    title:       "Building a REST API with Node.js and Express",
    description: "A ground-up tutorial for the EduTrack Rwanda backend. Covers routing, middleware, database connections, and environment variables.",
    author:      "Emile Nshimyimana",
    authorRole:  "Backend Engineer",
    readTime:    "20 min read",
    difficulty:  "intermediate",
    tags:        ["node.js", "express", "api", "javascript"],
    link:        "#",
    featured:    false,
    date:        "May 2025",
    views:       721,
  },
  {
    id:          6,
    slug:        "open-source-career-story",
    type:        "article",
    category:    "career",
    title:       "How Open Source Changed My Career — And How It Can Change Yours",
    description: "Amina Uwase went from student to Andela engineer partly through OSK. Here she breaks down how open source contribution accelerated her trajectory.",
    author:      "Amina Uwase",
    authorRole:  "Software Developer, Andela",
    readTime:    "6 min read",
    difficulty:  "beginner",
    tags:        ["career", "open source", "story", "job hunting"],
    link:        "#",
    featured:    false,
    date:        "April 2025",
    views:       1830,
  },
  {
    id:          7,
    slug:        "design-contribution-guide",
    type:        "guide",
    category:    "design",
    title:       "Contributing to Open Source as a Designer",
    description: "Most design contribution guides are written by engineers. This one isn't. Clarisse walks through the entire design contribution workflow from Figma to merged PR.",
    author:      "Clarisse Iradukunda",
    authorRole:  "UI/UX Designer",
    readTime:    "10 min read",
    difficulty:  "beginner",
    tags:        ["design", "figma", "contribution", "ux"],
    link:        "#",
    featured:    false,
    date:        "April 2025",
    views:       541,
  },
  {
    id:          8,
    slug:        "django-beginners",
    type:        "tutorial",
    category:    "python",
    title:       "Django for Beginners — Build Your First Model and View",
    description: "Used in the EduTrack Rwanda sessions. Covers Django project setup, models, views, URL routing, and the admin panel — all from scratch.",
    author:      "Tech Lead",
    authorRole:  "OSK Maintainer",
    readTime:    "25 min read",
    difficulty:  "beginner",
    tags:        ["python", "django", "backend", "web"],
    link:        "#",
    featured:    false,
    date:        "March 2025",
    views:       488,
  },
  {
    id:          9,
    slug:        "github-issue-pr-templates",
    type:        "template",
    category:    "open-source",
    title:       "GitHub Issue & PR Templates for OSK Projects",
    description: "Copy-paste templates for bug reports, feature requests, and pull request descriptions. Standardises contributor communication across all OSK repositories.",
    author:      "Solange Mukamana",
    authorRole:  "Technical Writer",
    readTime:    "2 min setup",
    difficulty:  "beginner",
    tags:        ["github", "templates", "issues", "prs"],
    link:        "#",
    featured:    false,
    date:        "March 2025",
    views:       392,
  },
];

export const EXTERNAL_TOOLS: ExternalTool[] = [
  {
    name:        "GitHub",
    description: "Where all OSK projects live. Your profile here is your most important portfolio.",
    link:        "https://github.com",
    iconKey:     "github",
    category:    "Version control",
    free:        true,
  },
  {
    name:        "VS Code",
    description: "The editor used by most OSK contributors. Extensive extensions, Git built-in.",
    link:        "https://code.visualstudio.com",
    iconKey:     "vscode",
    category:    "Editor",
    free:        true,
  },
  {
    name:        "Figma",
    description: "Design tool for OSK's UI/UX contributors. Free for individuals.",
    link:        "https://figma.com",
    iconKey:     "figma",
    category:    "Design",
    free:        true,
  },
  {
    name:        "Vercel",
    description: "Where most OSK frontend projects are deployed. One-click from GitHub.",
    link:        "https://vercel.com",
    iconKey:     "vercel",
    category:    "Deployment",
    free:        true,
  },
  {
    name:        "Postman",
    description: "API testing tool used during AfyaConnect and EduTrack Rwanda development.",
    link:        "https://postman.com",
    iconKey:     "postman",
    category:    "API Testing",
    free:        true,
  },
  {
    name:        "YouTube — OSK Sessions",
    description: "Recorded Wednesday sessions. Full replays of every technical session we've run.",
    link:        "https://www.youtube.com/@opensourcekigali",
    iconKey:     "youtube",
    category:    "Videos",
    free:        true,
  },
];

// Learning path data — used by the 3-path section
export const LEARNING_PATHS = [
  {
    key:     "developers",
    color:   "blue",
    icon:    "terminal",
    label:   "Path 1 — Developers",
    heading: "New to open source?\nStart here.",
    items: [
      "Your First Pull Request: A Complete Walkthrough",
      "How to Read Someone Else's Codebase",
      "Git Rebase vs Merge — Explained Simply",
    ],
    filterType:     "tutorial" as const,
    filterCategory: "git"      as const,
  },
  {
    key:     "designers",
    color:   "violet",
    icon:    "layout",
    label:   "Path 2 — Designers",
    heading: "Never opened a PR?\nThat's okay.",
    items: [
      "Contributing to Open Source as a Designer",
      "Your First Pull Request: A Complete Walkthrough",
      "OSK Project README Template",
    ],
    filterType:     "all"    as const,
    filterCategory: "design" as const,
  },
  {
    key:     "writers",
    color:   "emerald",
    icon:    "rss",
    label:   "Path 3 — Writers",
    heading: "Words are code too.\nStart writing.",
    items: [
      "OSK Project README Template",
      "GitHub Issue & PR Templates for OSK Projects",
      "How Open Source Changed My Career",
    ],
    filterType:     "all"    as const,
    filterCategory: "career" as const,
  },
];