import type { TeamMember } from "@/types";

export const TEAM: TeamMember[] = [
  {
    id: 1,
    name: "Didas Mbarushimana Daniel",
    role: "community-lead",
    label: "Community Lead",
    bio: "Defines the vision, represents OSK externally, and makes sure the Community is always moving forward.",
    initials: "DD",
    avatarBg: "#2b7fff",
    links: {
      github: "https://github.com",
      linkedin: "https://linkedin.com",
    },
    featured: true,
    handles: ["Partnerships", "Press", "Vision"],
  },
  {
    id: 2,
    name: "Operations Lead",
    role: "operations-lead",
    label: "Operations Lead",
    bio: "Turns strategy into execution — coordinating teams, tracking progress, and clearing blockers.",
    initials: "OL",
    avatarBg: "#1a6fef",
    links: {},
    featured: false,
    handles: ["Events", "Logistics", "Scheduling"],
  },
  {
    id: 3,
    name: "Tech Lead",
    role: "tech-lead",
    label: "Tech Lead",
    bio: "Sets the technical bar for all OSK projects. Reviews PRs, mentors contributors, and defines standards.",
    initials: "TL",
    avatarBg: "#0a5fdf",
    links: { github: "https://github.com" },
    featured: false,
    handles: ["Project proposals", "Code reviews", "GitHub"],
  },
  {
    id: 4,
    name: "Community Manager",
    role: "community-manager",
    label: "Community Manager",
    bio: "Your first point of contact. Makes sure every new member finds their place and every existing one stays engaged.",
    initials: "CM",
    avatarBg: "#5b9fff",
    links: {},
    featured: false,
    handles: ["Onboarding", "General questions", "Discord"],
  },
];
